app.id: es-operation-service
spring:
  application:
    name: ${app.id}
  cloud:
    nacos:
      discovery:
        server-addr: 10.19.160.197:8848
server:
  port: 10003

feign.okhttp.enabled : true


elasticsearch:
  client:
    address: 10.19.151.115:9200
    connectTimeOut: 1000
    socketTimeOut: 10000
    connectionRequestTime: 500
    maxConnectTotalNum: 50
    maxConnectPerRoute: 10
  service:
    scrollSort: false #游标下排序


